defaultDescription: Vibe packs digital whiteboard technology, video conferencing, wireless screencasting, third-party app integrations, and more into a sleek package.
stylesPath: css/styles.sass
appURL: https://app.vibe-beta.com/
apiURL: https://api.vibe-beta.com/v1/
allowIndex: false
