defaultDescription: Vibe packs digital whiteboard technology, video conferencing, wireless screencasting, third-party app integrations, and more into a sleek package.
appURL: https://app.vibe-beta.com/
apiURL: https://api.vibe-beta.com/v1/
allowIndex: false
microsoftIdentityAssociation: "e11766e4-36e3-426a-80fb-b357f1a8bbfc"
