name: 'Deployment'
on:
  push:
    branches:
      - master
  deployment:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Hugo 0.68.3
        run: |
          HUGO_VER=0.68.3
          HUGO_ZIP=hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz
          curl -OL https://github.com/gohugoio/hugo/releases/download/v$HUGO_VER/$HUGO_ZIP
          sudo tar xf $HUGO_ZIP -C /usr/local/bin hugo
          rm -f $HUGO_ZIP
      - name: Pip install
        run: |
          pip3 install -r requirements.txt
      - name: Yarn install
        run: yarn install
      - name: Sync blogs
        if: github.event_name == 'deployment' && github.event.deployment.task == 'sync-blogs'
        env:
          VIBE_CMS_TOKEN: ${{ secrets.VIBE_CMS_TOKEN }}
        run: |
          python3 sync-cms blog
          git config user.name '${{ github.event.deployment.creator.login }} via GitHub Actions'
          git config user.email '${{ github.event.deployment.creator.login }}@users.noreply.github.com'
          if git add -A && git commit -m "Sync blogs using ./sync-cms command"; then
            git push
          fi
      - name: Sync video tutorials
        if: github.event_name == 'deployment' && github.event.deployment.task == 'sync-videos'
        env:
          VIBE_CMS_TOKEN: ${{ secrets.VIBE_CMS_TOKEN }}
        run: |
          python3 sync-cms video
          git config user.name '${{ github.event.deployment.creator.login }} via GitHub Actions'
          git config user.email '${{ github.event.deployment.creator.login }}@users.noreply.github.com'
          if git add -A && git commit -m "Sync videos using ./sync-cms command"; then
            git push
          fi
      - name: Hugo build and deploy staging
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'deployment' && github.event.deployment.environment == 'staging')
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          rm -rf public/
          hugo -e staging --minify
          hugo deploy --target aws-staging --maxDeletes -1 --invalidateCDN
      - name: Hugo build and deploy production
        if: github.event_name == 'deployment' && github.event.deployment.environment == 'production' && github.ref == 'refs/heads/master'
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          rm -rf public/
          hugo -e production --minify
          hugo deploy --target aws-production --invalidateCDN
      - name: Hugo build and deploy cn production
        if: github.event_name == 'deployment' && github.event.deployment.environment == 'production' && github.ref == 'refs/heads/master'
        env:
          AWS_DEFAULT_REGION: cn-northwest-1
          AWS_ACCESS_KEY_ID: ${{ secrets.CN_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CN_AWS_SECRET_ACCESS_KEY }}
        run: |
          rm -rf public/
          hugo -e cn-production --minify
          hugo deploy --target aws-cn-production --invalidateCDN
          # additional CDN for vibe.cn, not used but just to keep it up to date until we turn it off.
          aws cloudfront create-invalidation --distribution-id E10VE47GZ51NZB
      - uses: actions/github-script@0.3.0
        if: github.event_name == 'deployment'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createDeploymentStatus({
              owner: 'vibeus',
              repo: '${{ github.event.repository.name }}',
              deployment_id: '${{ github.event.deployment.id }}',
              state: 'success',
            })
      - uses: actions/github-script@0.3.0
        if: github.event_name == 'deployment' && (failure() || cancelled())
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createDeploymentStatus({
              owner: 'vibeus',
              repo: '${{ github.event.repository.name }}',
              deployment_id: '${{ github.event.deployment.id }}',
              state: 'failure',
            })
